/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData orderForm = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData findings = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData personal = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe615, fontFamily: 'MyIcons2');
  static const IconData placeholder = const IconData(0xe627, fontFamily: 'MyIcons2');
  static const IconData addressholder = const IconData(0xe60d, fontFamily: 'MyIcons3');
  static const IconData youhuiquanholder = const IconData(0xe645, fontFamily: 'MyIcons3');
  static const IconData jifenholder = const IconData(0xe624, fontFamily: 'MyIcons3');
  static const IconData liwuholder = const IconData(0xe60b, fontFamily: 'MyIcons3');
  static const IconData daifukuan = const IconData(0xe632, fontFamily: 'MyIcons3');
  static const IconData daifahuo = const IconData(0xe63e, fontFamily: 'MyIcons3');
  static const IconData yifahuo = const IconData(0xe620, fontFamily: 'MyIcons3');
  static const IconData yiwancheng = const IconData(0xe6d7, fontFamily: 'MyIcons3');
  static const IconData zhifubpay = const IconData(0xe68a, fontFamily: 'MyIcons4');
  static const IconData weixinpay = const IconData(0xe61b, fontFamily: 'MyIcons4');
  static const IconData sexicon = const IconData(0xe611, fontFamily: 'MyIcons4');
}
